name: shn-pyshs
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - ipykernel
  - pathlib
  - plotly
  - matplotlib
  - scipy
  - pandas
  - xlrd
  - seaborn
  - statsmodels
  - patsy
